---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/airports":
    get:
      summary: Fetches Airports
      tags:
      - Airport
      parameters:
      - name: countries[]
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Airports found
          content:
            application/json:
              schema:
                type: object
                properties:
                  airports:
                    type: array
                    items:
                      type: object
                      properties:
                        iata:
                          type: string
                        name:
                          type: string
                        country:
                          type: string
                        id:
                          type: string
                      additionalProperties: false
                      required:
                      - name
                      - iata
                      - country
                      - id
                required:
                - airports
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
